=== aht-group/ofx/tags/ofx-1.3.1/old/applications/fuxml/formats/html/dtd/conversionlist.dtd
<!ELEMENT CharacterConversionList (Entry+, AttributeInclusionList, ElementExclusionList)>
<!ELEMENT Entry (From, To)>
<!ELEMENT From (#PCDATA)>
<!ELEMENT To (#PCDATA)>
<!ELEMENT ElementExclusionList (Element+)>
<!ELEMENT AttributeInclusionList (Attribute+)>
<!ELEMENT Element (#PCDATA)>
<!ELEMENT Attribute (#PCDATA)>

=== aht-group/ofx/trunk/old/applications/fuxml/formats/latexpdf/remove_lf.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE CharacterConversionList SYSTEM "dtd/conversionlist.dtd">
<!-- ********************************************************************
	$Id: remove_lf.xml,v 1.3 2007/01/17 13:06:27 hemmer Exp $
	********************************************************************
*******************************************************************************
	| openFuXML open source                                                       |
*******************************************************************************
	| Copyright (c) 2002-2006 openFuXML open source, University of Hagen          |
	|                                                                             |
	| This program is free software; you can redistribute it and/or               |
	| modify it under the terms of the GNU General Public License                 |
	| as published by the Free Software Foundation; either version 2              |
	| of the License, or (at your option) any later version.                      |
	|                                                                             |
	| This program is distributed in the hope that it will be useful,             |
	| but WITHOUT ANY WARRANTY; without even the implied warranty of              |
	| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               |
	| GNU General Public License for more details.                                |
	|                                                                             |
	| You should have received a copy of the GNU General Public License           |
	| along with this program; if not, write to the Free Software                 |
	| Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. |
*******************************************************************************
	******************************************************************** -->
<CharacterConversionList>
	<Entry>
		<From>&#xA;</From>
		<To/>
	</Entry>
	<!--List of elements for which character conversion does not apply-->
	<AttributeInclusionList>
		<Attribute>dummy</Attribute>
	</AttributeInclusionList>
	<ElementExclusionList>
		<Element>buchstaeblich</Element>
	</ElementExclusionList>
</CharacterConversionList>
